config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/bench_event_api:
      branch: master
      repo: https://github.com/EOSC-synergy/bench_event_api
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-only_im_client
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/bench_event_api git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-champagne-hummingbird.sh
        container: qc.acc_scummy-saffron-havanese
  QC.Doc:
    repos:
      github.com/EOSC-synergy/bench_event_api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-denim-giraffe.sh
        container: qc.doc_snappy-indigo-weasel
      github.com/EOSC-synergy/bench_event_api git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-orchid-affenpinscher.sh
        container: qc.doc_blurry-mustard-starfish
      github.com/EOSC-synergy/bench_event_api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-xanthic-newfoundland.sh
        container: qc.doc_shabby-goldenrod-mandrill
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/bench_event_api F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-grey-turkey.sh
        container: qc.fair_baggy-lilac-burmese
  QC.Lic:
    repos:
      github.com/EOSC-synergy/bench_event_api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-indigo-dingo.sh
        container: qc.lic_flaky-cinnamon-eagle
  QC.Sec:
    repos:
      github.com/EOSC-synergy/bench_event_api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-gold-koala.sh
        container: qc.sec_droopy-cardinal-clam
  QC.Sty:
    repos:
      github.com/EOSC-synergy/bench_event_api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-magenta-blue.sh
        container: qc.sty_chewy-violet-bison
  QC.Ver:
    repos:
      github.com/EOSC-synergy/bench_event_api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-ultramarine-ocelot.sh
        container: qc.ver_stealthy-seashell-grasshopper
timeout: 1800
